// Best-effort Vietnamese/English labels lifted from each entry form's <label>
// text, keyed by DB field name. Any DB field not covered here (or entries
// here with no matching DB field) is harmless — excel.js falls back to a
// title-cased version of the field key for anything missing.

const TRADES = {
  contract_no: 'Contract No (số hợp đồng)',
  staff: 'Staff (nhân viên)', broker: 'Broker (môi giới)', year: 'Year (năm)',
  status: 'Status (trạng thái)', contract_date: 'Date (ngày phát hành)',
  seller: 'Seller (bên bán)', buyer: 'Buyer (bên mua)', ship_date: 'Ship (thời gian giao)',
  qty: 'Qty (tấn)', origin: 'Origin (nguồn gốc)', pol: 'POL (cảng chất hàng)',
  lbs: 'LBs (chất lượng 1)', nut: 'Nut (chất lượng 2)', price: 'Price ($/tấn)',
  retention: 'Retention (%)', double_penalty: 'Double Penalty', notes1: 'Notes 1 (ghi chú hợp đồng)',
  advanced_payment: 'Advanced Payment ($) - Tiền cọc', second_payment: 'Second Payment ($) - Tiền cọc lần 2',
  final_settlement: 'Final Settlement - Quyết toán cuối', line_loader: 'Line/Loader (chi tiết bill)',
  bl_number: 'B/L Number (số bill)', eta_caimep: 'ETA CAIMEP', eta_hcm: 'ETA HCM',
  eta_pod: 'ETA POD (thực tế)', notes2: 'Notes 2 (ghi chú bill)',
  dhl_fedex_number: 'DHL/Fedex Number (số chứng từ)', dhl_delivered: 'DHL Delivered (ngày giao chứng từ)',
  total_cont: 'Total Cont', cont_size: 'Cont Size', bags: 'Bags',
  gw_bl: 'GW on B/L (MT)', nw_bl: 'NW on B/L (MT)', advanced_paid_bl: 'Advanced Paid B/L ($)',
  date_unload: 'Date Unload Cargo (ngày dỡ hàng)', notes3: 'Notes 3 (ghi chú kiểm tra)',
  certificate_no: 'Vina/CF Certificate No (số chứng nhận)', date_certificate: 'Date of Certificate (ngày cấp CN)',
  nw_bw: 'NW out of BW (MT) - Trọng lượng CN', outturn_vina: 'Outturn Vina/CF - Chất lượng 1 trên CN',
  nutcount_vina: 'Nutcount Vina/CF - Chất lượng 2 trên CN',
  outturn_claim_1to1: '1:1 Outturn Claim ($)', outturn_claim_1to2: '1:2 Outturn Claim ($)',
  dem_det: 'DEM/DET ($)', sto: 'STO ($)', other_fee1: 'Other Fee 1 ($)', other_fee2: 'Other Fee 2 ($)',
  notes6: 'Notes 6 (ghi chú)', commission_rate: 'Commissions ($/MT) - Hoa hồng đơn vị',
  pay_on_behalf: 'Pay on behalf of Seller ($)', fee_from_buyer: 'Fee has to take from Buyer ($)',
  notes7: 'Notes 7',
};

const IMPORT_RECORDS = {
  year: 'Year', staff: 'Staff', vn_broker: 'VN Broker', agency: 'Agency', order_note: 'Order/Note',
  sale_contract: 'Sale Contract', date: 'Date', seller: 'Seller (bên bán)', buyer: 'Buyer (bên mua)',
  status: 'Status', shipment: 'Shipment (ngày giao hàng)', quantity: 'Quantity (MT)',
  origin: 'Origin', pol: 'POL', outturn: 'Outturn (lbs)', nutcount: 'Nutcount', moisture: 'Moisture',
  price: 'Price ($/MT)', pct1: '1st (%)', pct2: '2nd (%)', pct3: '3rd (%)',
  double_penalty: 'Double Penalty below (lbs, số dương)', penalty_1to1: '1:1 Penalty ($) - để trống = tự tính Price/Outturn',
  penalty_1to2: '1:2 Penalty ($) - để trống = tự tính 1:1 x 2',
  nutcount_penalty: 'Nutcount Penalty ($)', moisture_penalty: 'Moisture Penalty ($)',
  advanced_payment: 'Prepayment / 1st Payment ($)', payment_date1: 'Payment Date 1', note_pay: 'Note Payment',
  date_unload: 'Date Unload Cargo', notes_cert: 'Supervisor', certificate_no: 'Vina/Cafecontrol Certificate No',
  date_certificate: 'Date of Certificate', nw_bw: 'NW as Vina/CF or NW out of BWH (MT)',
  outturn_vina: 'Outturn Vina/CF (lbs)', nutcount_vina: 'Nutcount Vina/CF', moisture_vina: 'Moisture Vina/CF',
  dem_det: 'DEM/DET ($)', sto: 'STO ($)', other_fee1: 'Other Fee 1 ($)', other_fee2: 'Other Fee 2 ($)',
  debit_credit_input: 'Debit/Credit (Buyer/Seller input) ($)', notes_final: 'Notes Final',
  commission1_usd_mt: 'Commission 1 ($/MT)', pay_on_behalf1: 'Pay on behalf of Seller 1 ($)',
  notes_comm1: 'Notes Commission 1', commission2_usd_mt: 'Commission 2 ($/MT)',
  pay_on_behalf2: 'Pay on behalf of Seller 2 ($)', notes_comm2: 'Notes Commission 2',
};

const EXPORT_RECORDS = {
  year: 'Year', staff: 'Staff', vn_broker: 'VN Broker', order_note: 'Order/Note', lot_number: 'Lot Number',
  sale_contract: 'Sale Contract', date: 'Date', status: 'Status',
  expiry_export_cert_turkey: 'Expiry date of Export Cert to Turkey',
  seller: 'Seller', buyer1: 'Buyer 1', buyer2: 'Buyer 2', commodity: 'Commodity',
  qty_commodity: 'Quantity Commodity + Loại cont', price: 'Price',
  shipment: 'Shipment', packing: 'Packing', packing_ctn: 'Packing CTN', packing_unit: 'Packing Unit',
  ctn_cont: 'CTN/CONT', quantity: 'Quantity', quantity_unit: 'Quantity Unit',
  advance_payment: 'Advance Payment', payment_date1: 'Payment Date 1', payment2: 'Payment 2',
  payment_date2: 'Payment Date 2', payment3: 'Payment 3', payment_date3: 'Payment Date 3', note_pay: 'Note Payment',
  market: 'Market', crd: 'CRD', req_get_bkg: 'Req Get BKG', inspection_date: 'Inspection Date',
  loading_date: 'Loading Date', supervisor: 'Supervisor', fwd: 'FWD',
  ocean_freight: 'Ocean Freight ($)', note_booking: 'Note Booking', pol: 'POL', pod: 'POD',
  shipping_line: 'Shipping Line', etd: 'ETD', eta: 'ETA',
  bkg_details: 'BKG Details', container_seal: 'Container/Seal Number', bl_bkg_freetime: 'BL/BKG/Freetime',
  seller_invoice_no: 'Seller Invoice Number', note_shipping: 'Note Shipping',
  commodity2: 'Commodity 2', total_cont: 'Total Cont', ctn2: 'CTN',
  gw_bl_lbs: 'GW on B/L (lbs)', gw_bl_kgs: 'GW on B/L (kgs)', nw_bl_lbs: 'NW on B/L (lbs)', nw_bl_kgs: 'NW on B/L (kgs)',
  nw_to_pay: 'NW to Pay', nw_to_pay_unit: 'NW to Pay Unit',
  less_advance: 'Less Advance (-) ($)', discount1: 'Discount (-) ($)', other_fee1: 'Other Fee 1 ($)',
  include_other_fee: 'Include Other Fee', seller_invoice_amount: 'Seller Invoice Amount ($)', note_invoice: 'Note Invoice',
  ins_company: 'INS Company', ins_fee: 'INS Fee ($)', pct_insured: 'Percentage Insured (%)',
  ins_rate: 'Rate (%)', ins_vat: 'VAT (%)', exchange_rate_usd_vnd: 'Exchange Rate (USD-VND)',
  ins_duration: 'Duration', ins_payment_date: 'INS Payment Date', note_ins: 'Note INS',
  dhl_fedex_number: 'DHL/Fedex Number', dhl_delivered: 'DHL Delivered', dhl_fee: 'DHL Fee', note_dhl: 'Note DHL',
  selling_price: 'Selling Price ($)', mark_up: 'Mark Up ($)', discount2: 'Discount 2 (-) ($)', other_fee2: 'Other Fee 2 ($)',
  amount_buyer2_paid: 'Amount Buyer 2 Paid', payment_date_buyer2: 'Payment Date Buyer 2',
  cosmos_rate: 'Cosmos Rate ($)', cosmos_payment_date: 'Cosmos Payment Date', note_cos: 'Note Cosmos',
  commission_usd_lbs: 'Commission ($/lbs)', rate_exchange_vnd: 'Rate of Exchange (VND)',
  commission_payment_date: 'Commission Payment Date', note_com: 'Note Commission',
};

const BWH_RECORDS = {
  year: 'Year', bwh: 'BWH', no: 'No', seller: 'Seller', bl: 'BL', status: 'Status',
  eta_vung_tau: 'ETA Vũng Tàu', eta_hcm: 'ETA HCM', total_cont: 'Total Cont', total_bags: 'Total Bags',
  gross_weight: 'Gross Weight (MT)', net_weight: 'Net Weight (MT)', origin: 'Origin', commodity: 'Commodity',
  price_bwh_inventory: 'Price for BWH Inventory ($)', inv_number: 'Inv Number', note_tt_kho: 'Note TT Kho',
  date_into_bwh: 'Date Into BWH', supervisor_in: 'Supervisor (nhập)', gw_into_bwh: 'GW Into BWH (MT)',
  nw_into_bwh: 'NW Into BWH (MT)', note_into_bwh: 'Note (thiếu hụt khi nhập kho)',
  date_out_bwh: 'Date Out of BWH', supervisor_out: 'Supervisor (xuất)', gw_out_bwh: 'GW Out of BWH (MT)',
  nw_out_bwh: 'NW Out of BWH (MT)', note_out_bwh: 'Note (thiếu hụt khi xuất kho)',
  ins_company: 'INS Company', ins_fee: 'INS Fee ($)', pct_insured: '% Insured', ins_rate: 'Rate (%)',
  ins_vat: 'VAT (%)', exchange_rate: 'Exchange Rate (VND)', ins_duration: 'Duration',
  ins_payment_date: 'INS Payment Date', note_ins: 'Note INS',
  deposit: 'Deposit ($)', deposit_payment_date: 'Payment Date (Deposit)', amount_paid: 'Amount Paid ($)',
  amount_paid_date: 'Payment Date (Amount)', note_pay_bwh: 'Note Pay BWH',
};

module.exports = { TRADES, IMPORT_RECORDS, EXPORT_RECORDS, BWH_RECORDS };
